### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by jargonfilter** [yzhouas/PD-Denoising-pytorch#2]
I realize that: 

> "This version of testing script may cause exceeding memory issues in GPU while testing on large images. A testing_on_full image version will be released soon."

But I encountered this issue on an 8GB RTX 2070 on ubuntu 18.04 while trying run_test_on_real_patches.sh

I can confirm that it runs just fine when I resize the provided sample images to 300x300px.

Does this seem right? Will a new version of the script solve this problem? Any idea how soon that might be released? 

Thanks!

**Comment by yzhouas** [comment]
I am not sure but it should be fine with images of 512x512. The testing-on-full-image version is to crop larger images to smaller patches for denoising and then combine them back. It will solve the out-of-memory issue but increase the execution time. If needed, I will release it in a few days.

**Comment by yzhouas** [comment]
Codes updated.

**Comment by jargonfilter** [comment]
Wow thanks for taking the time out of your weekend to do that! I'll try to test it tonight or tomorrow evening.

**Comment by jargonfilter** [comment]
Just tested with your larger example images. Seems to work! Thanks!

**Comment by Tetsujinfr** [comment]
Thanks for the repo, works on first time. Initially I tried the full frame inference code, and that was burning over 8GB of memory to process a 672x344 frame!! (including 3gb of swap memory on my limited but capable embedded system)
But then I saw this issue thread and I continued to read until the end of the repo readme and tried the `Demo_on_full_image.py` instead of `test.py` : that worked brilliantly. Actually it ran much faster and is much more stable on my system given that it did not use any swap memory.

I think you should highlight the memory friendly option earlier in your readme, like a mention "**For limited memory users, I recommend using the Demo_on_full_image.py, see down below.**"

I did not notice any clear artefact in the memory friendly inference, real nice job.
I attach an example of an original image, the full frame processed one, and the cropped processed one (wbin=256, did consume around 3GB of memory max) for anyone interested.

![original](https://user-images.githubusercontent.com/29961693/120567055-b9bebe00-c408-11eb-99b0-28d32a5da292.jpg)

![denoised_full_frame](https://user-images.githubusercontent.com/29961693/120567065-be837200-c408-11eb-974d-e82d37b227fb.png)

![denoised_tiles](https://user-images.githubusercontent.com/29961693/120567071-c2af8f80-c408-11eb-8dd3-1477b33cc19c.png)
